#output should be IntentType, PriorityLevel, Sentiment, SupervisorDecision

#each information, if produced by supervisor, then SupervisorDecision, else it is part of GraphState
# try to make the fields to be enum 

from enum import Enum #restrict values like billing, technical etc
from pydantic import BaseModel, Field # basemodel - structured output, field: descriptions and validation

class IntentType(str, Enum):
    BILLING = "billing"
    TECHNICAL = "technical"
    RETURNS = "returns"
    ESCALATION = "escalation"


class PriorityLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"

class Sentiment(str, Enum):
    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"

class SupervisorDecision(BaseModel):
    """
    Structured routing decision generated by the Supervisor Agent.

    This model is consumed by LangGraph routing and downstream agents.
    """
    intent: IntentType = Field(..., description="The intent of the user query")
    priority: PriorityLevel = Field(..., description="The priority level of the user query")
    sentiment: Sentiment = Field(..., description="The sentiment of the user query")
    ticket_summary: str = Field(..., description="A summary of the user query")
    confidence: float = Field(ge=0, le=1,  description="The confidence level of the supervisor's decision, between 0 and 1")
    requires_human: bool = Field(..., description="Indicates whether the supervisor's decision requires human intervention")
    reasoning: str | None = Field(..., description="The reasoning behind the supervisor's decision")
    next_agent: IntentType = Field(..., description="The next agent to handle the user query, the intent is same as the next agent ")
